repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1  # можно заменить на твою установленную версию (gitleaks --version)
    hooks:
      - id: gitleaks
        name: gitleaks (detect secrets)
        entry: gitleaks detect --source . --no-git --config .gitleaks.toml
        language: system
        pass_filenames: false
